import java.awt.*;
import javax.swing.*;
import java.awt.event.*;
import java.sql.*;
import java.util.*;
import com.toedter.calendar.JDateChooser;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
public class Empadd extends JFrame implements ActionListener {
    JLabel l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13, l14, l15, l16, l17, l18,l19,l20,l21,l22,l23,l24,l25,l26,l27;
    JTextField t1, t2, t3, t4, t5, t6, t7, t8, t9, t10,t11,t12,t13;
    JRadioButton r1, r2, r3, r4, r5,r6,r7,r8,r9;
    JButton b1,b2;
    JDateChooser dateChooser,dateChooser1,dateChooser2,dateChooser3;
    JComboBox c1,c2,c3,c4,c5,c6;
    Random ran = new Random();
    long first4 = (ran.nextLong() % 9000L) + 1000L;
    String first = " " + Math.abs(first4);
    Empadd() {
        setFont(new Font("system", Font.BOLD, 22));
        Font f = getFont();
        FontMetrics fm = getFontMetrics(f);
        int x = fm.stringWidth("NEW ACCOUNT APPLICATION FORM");
        int y = fm.stringWidth(" ");
        int z = getWidth() - x;
        int w = z / y;
        String pad = "";
        pad = String.format("%" + w + "s", pad);
        setTitle(pad + pad + pad + "NEW EMPLOYEE FORM");
        ImageIcon i1 = new ImageIcon(ClassLoader.getSystemResource("icons/logo.jpg"));
        Image i2 = i1.getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT);
        ImageIcon i3 = new ImageIcon(i2);
        JLabel l11 = new JLabel(i3);
        l11.setBounds(220, 10, 100, 100);
        add(l11);
        l1 = new JLabel("NEW EMPLOYEE FORM");
        l1.setFont(new Font("Raleway", Font.BOLD, 38));
        l2 = new JLabel("Employee Details");
        l2.setFont(new Font("Raleway", Font.BOLD, 22));
        l3 = new JLabel("Name:");
        l3.setFont(new Font("Raleway", Font.BOLD, 20));
        l4 = new JLabel("Father's  Name:");
        l4.setFont(new Font("Raleway", Font.BOLD, 20));
        l5 = new JLabel("Mother's  Name:");
        l5.setFont(new Font("Raleway", Font.BOLD, 20));
        l17 = new JLabel("Guardian's  Name:");
        l17.setFont(new Font("Raleway", Font.BOLD, 20));
        l18 = new JLabel("Mobile No.:");
        l18.setFont(new Font("Raleway", Font.BOLD, 20));
        l6 = new JLabel("Date Of Birth:");
        l6.setFont(new Font("Raleway", Font.BOLD, 20));
        l7 = new JLabel("Gender:");
        l7.setFont(new Font("Raleway", Font.BOLD, 20));
        l8 = new JLabel("Email Address:");
        l8.setFont(new Font("Raleway", Font.BOLD, 20));
        l9 = new JLabel("Marital Status:");
        l9.setFont(new Font("Raleway", Font.BOLD, 20));
        l10 = new JLabel("Address:");
        l10.setFont(new Font("Raleway", Font.BOLD, 20));
        l11 = new JLabel("City:");
        l11.setFont(new Font("Raleway", Font.BOLD, 20));
        l12 = new JLabel("Pin Code:");
        l12.setFont(new Font("Raleway", Font.BOLD, 20));
        l13 = new JLabel("State:");
        l13.setFont(new Font("Raleway", Font.BOLD, 20));
        l14 = new JLabel("Date: ");
        l14.setFont(new Font("Raleway", Font.BOLD, 20));
        l15 = new JLabel("Month:");
        l15.setFont(new Font("Raleway", Font.BOLD, 20));
        l16 = new JLabel("Year");
        l16.setFont(new Font("Raleway", Font.BOLD, 20));
        l19 = new JLabel("Aadhar number:");
        l19.setFont(new Font("Raleway", Font.BOLD, 20));
        l20 = new JLabel("Pan card number:");
        l20.setFont(new Font("Raleway", Font.BOLD, 20));
        l21 = new JLabel("Religion:");
        l21.setFont(new Font("Raleway", Font.BOLD, 20));
        l22 = new JLabel("Designation:");
        l22.setFont(new Font("Raleway", Font.BOLD, 20));
        l23 = new JLabel("Qualification:");
        l23.setFont(new Font("Raleway", Font.BOLD, 20));
        l24 = new JLabel("Type of job:");
        l24.setFont(new Font("Raleway", Font.BOLD, 20));
        l25 = new JLabel("Appoinment letter Date:");
        l25.setFont(new Font("Raleway", Font.BOLD, 20));
        l26 = new JLabel("Place of Posting:");
        l26.setFont(new Font("Raleway", Font.BOLD, 20));
        l27 = new JLabel("Category:");
        l27.setFont(new Font("Raleway", Font.BOLD, 20));
        r6=new JRadioButton("Permarent");
        r6.setFont(new Font("Raleway",Font.BOLD,14));
        r6.setBackground(Color.WHITE);
        r7=new JRadioButton("Contractual");
        r7.setFont(new Font("Raleway",Font.BOLD,14));
        r7.setBackground(Color.WHITE);
        ButtonGroup groupy=new ButtonGroup();
        groupy.add(r6);
        groupy.add(r7);
        t1 = new JTextField();
        t1.setFont(new Font("Raleway", Font.BOLD, 14));
        t2 = new JTextField();
        t2.setFont(new Font("Raleway", Font.BOLD, 14));
        t3 = new JTextField();
        t3.setFont(new Font("Raleway", Font.BOLD, 14));
        t4 = new JTextField();
        t4.setFont(new Font("Raleway", Font.BOLD, 14));
        t5 = new JTextField();
        t5.setFont(new Font("Raleway", Font.BOLD, 14));
        t6 = new JTextField();
        t6.setFont(new Font("Raleway", Font.BOLD, 14));
        t7 = new JTextField();
        t7.setFont(new Font("Raleway", Font.BOLD, 14));
        t8 = new JTextField();
        t8.setFont(new Font("Raleway", Font.BOLD, 14));
        t9 = new JTextField();
        t9.setFont(new Font("Raleway", Font.BOLD, 14));
        t10 = new JTextField();
        t10.setFont(new Font("Raleway", Font.BOLD, 14));
        t11 = new JTextField();
        t11.setFont(new Font("Raleway", Font.BOLD, 14));
        t12 = new JTextField();
        t12.setFont(new Font("Raleway", Font.BOLD, 14));
        t13 = new JTextField();
        t13.setFont(new Font("Raleway", Font.BOLD, 14));
        b1 = new JButton("ADD");
        b1.setFont(new Font("Raleway", Font.BOLD, 14));
        b1.setBackground(Color.BLACK);
        b1.setForeground(Color.WHITE);
        b2 = new JButton("Cancel");
        b2.setFont(new Font("Raleway", Font.BOLD, 14));
        b2.setBackground(Color.BLACK);
        b2.setForeground(Color.WHITE);
        r1 = new JRadioButton("Male");
        r1.setFont(new Font("Raleway", Font.BOLD, 14));
        r1.setBackground(Color.WHITE);
        r2 = new JRadioButton("Female");
        r2.setFont(new Font("Raleway", Font.BOLD, 14));
        r2.setBackground(Color.WHITE);
        ButtonGroup groupgender = new ButtonGroup();
        groupgender.add(r1);
        groupgender.add(r2);
        r3 = new JRadioButton("Married");
        r3.setFont(new Font("Raleway", Font.BOLD, 14));
        r3.setBackground(Color.WHITE);
        r4 = new JRadioButton("Unmarried");
        r4.setFont(new Font("Raleway", Font.BOLD, 14));
        r4.setBackground(Color.WHITE);
        r5 = new JRadioButton("Others");
        r5.setFont(new Font("Raleway", Font.BOLD, 14));
        r5.setBackground(Color.WHITE);
        ButtonGroup groupsatatus = new ButtonGroup();
        groupsatatus.add(r3);
        groupsatatus.add(r4);
        groupsatatus.add(r5);
        String religion[]={"Hindu","Muslim","Sikh","Christian","Other"};
        c1 = new JComboBox(religion);
        c1.setBackground(Color.WHITE);
        c1.setFont(new Font("Raleway",Font.BOLD,14));
        String designation[]={"Manager","Deputy Manager","Service Manager","Cashier","Clerk","Other"};
        c2 = new JComboBox(designation);
        c2.setBackground(Color.WHITE);
        c2.setFont(new Font("Raleway",Font.BOLD,14));
        String Qualification[]={"B.sc","B.com","M.sc","M.com","B.A.","B.B.A.","M.B.A.","Other"};
        c3 = new JComboBox(Qualification);
        c3.setBackground(Color.WHITE);
        c3.setFont(new Font("Raleway",Font.BOLD,14));
        String location[]={"Andhra Pradesh","Arunachal Pradesh","Assam","Bihar","Chhattisgarh","Goa","Gujarat","Haryana","Himachal Pradesh","Jharkhand","Karnataka","Kerala","Madhya Pradesh","Maharashtra","Manipur","Meghalaya","Mizoram","Nagaland","Odisha","Punjab","Rajasthan","Sikkim","Tamil Nadu","Telangana","Tripura","Uttar Pradesh","Uttarakhand","West Bengal"};
        c4 = new JComboBox(location);
        c4.setBackground(Color.WHITE);
        c4.setFont(new Font("Raleway",Font.BOLD,14));
        String category[]={"General","SC","ST","OBC","Other"};
        c5=new JComboBox(category);
        c5.setBackground(Color.WHITE);
        c5.setFont(new Font("Raleway",Font.BOLD,14));
        String Home[]={"Andhra Pradesh","Arunachal Pradesh","Assam","Bihar","Chhattisgarh","Goa","Gujarat","Haryana","Himachal Pradesh","Jharkhand","Karnataka","Kerala","Madhya Pradesh","Maharashtra","Manipur","Meghalaya","Mizoram","Nagaland","Odisha","Punjab","Rajasthan","Sikkim","Tamil Nadu","Telangana","Tripura","Uttar Pradesh","Uttarakhand","West Bengal"};
        c6 = new JComboBox(Home);
        c6.setBackground(Color.WHITE);
        c6.setFont(new Font("Raleway",Font.BOLD,14));
        dateChooser = new JDateChooser();
        dateChooser.setForeground(new Color(105, 105, 119));
        dateChooser.setBounds(137, 337, 200, 29);
        add(dateChooser);
        dateChooser1 = new JDateChooser();
        dateChooser1.setForeground(new Color(105, 105, 119));
        dateChooser1.setBounds(950, 440, 400, 30);
        add(dateChooser1);
        setLayout(null);
        l1.setBounds(390, 20, 800, 40);
        add(l1);
        l2.setBounds(590, 80, 800, 30);
        add(l2);
        l3.setBounds(70, 140, 100, 30);
        add(l3);
        t1.setBounds(270, 140, 400, 30);
        add(t1);
        l4.setBounds(70, 190, 200, 30);
        add(l4);
        t2.setBounds(270, 190, 400, 30);
        add(t2);
        l5.setBounds(70, 240, 200, 30);
        add(l5);
        t3.setBounds(270, 240, 400, 30);
        add(t3);
        l17.setBounds(70, 290, 200, 30);
        add(l17);
        t9.setBounds(270, 290, 400, 30);
        add(t9);
        l18.setBounds(70, 340, 200, 30);
        add(l18);
        t10.setBounds(270, 340, 400, 30);
        add(t10);
        l6.setBounds(70, 390, 400, 30);
        add(l6);
        dateChooser.setBounds(270, 390, 400, 30);
        l7.setBounds(70, 440, 200, 30);
        add(l7);
        r1.setBounds(270, 440, 60, 30);
        add(r1);
        r2.setBounds(420, 440, 90, 30);
        add(r2);
        l8.setBounds(70, 490, 200, 30);
        add(l8);
        t4.setBounds(270, 490, 400, 30);
        add(t4);
        l9.setBounds(70, 540, 200, 30);
        add(l9);
        r3.setBounds(270, 540, 100, 30);
        add(r3);
        r4.setBounds(420, 540, 100, 30);
        add(r4);
        r5.setBounds(590, 540, 100, 30);
        add(r5);
        l10.setBounds(70, 590, 200, 30);
        add(l10);
        t5.setBounds(270, 590, 400, 30);
        add(t5);
        l11.setBounds(70, 640, 200, 30);
        add(l11);
        t6.setBounds(270, 640, 400, 30);
        add(t6);
        l12.setBounds(70, 690, 200, 30);
        add(l12);
        t7.setBounds(270, 690, 400, 30);
        add(t7);
        l13.setBounds(70, 740, 200, 30);
        add(l13);
        c6.setBounds(270, 740, 200, 30);
        add(c6);
        l19.setBounds(700, 140, 240, 30);
        add(l19);
        t11.setBounds(950, 140, 400, 30);
        add(t11);
        l20.setBounds(700, 190, 200, 30);
        add(l20);
        t12.setBounds(950, 190, 400, 30);
        add(t12);
        l21.setBounds(700, 240, 200, 30);
        add(l21);
        c1.setBounds(950, 240, 400, 30);
        add(c1);
        l22.setBounds(700, 290, 200, 30);
        add(l22);
        c2.setBounds(950, 290, 400, 30);
        add(c2);
        l23.setBounds(700, 340, 200, 30);
        add(l23);
        c3.setBounds(950, 340, 400, 30);
        add(c3);
        l24.setBounds(700, 390, 200, 30);
        add(l24);
        r6.setBounds(950, 390, 150, 30);
        add(r6);
        r7.setBounds(1140, 390, 150, 30);
        add(r7);
        l25.setBounds(700, 440, 400, 30);
        add(l25);
        l26.setBounds(700, 490, 200, 30);
        add(l26);
        c4.setBounds(950, 490, 400, 30);
        add(c4);
        l27.setBounds(700, 540, 200, 30);
        add(l27);
        c5.setBounds(950, 540, 400, 30);
        add(c5);
        b1.setBounds(1150, 820, 80, 30);
        add(b1);
        b2.setBounds(1250, 820, 120, 30);
        add(b2);
        b1.addActionListener(this);
        b2.addActionListener(this);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                System.exit(0);
            }
        });
        getContentPane().setBackground(Color.WHITE);
        setSize(1500, 950);
        setLocation(250, 60);
        setVisible(true);

    }
    public void actionPerformed(ActionEvent ae) {
        if (ae.getSource() == b1) {
            String name = "\"" + t1.getText() + "\"";
            String fname = "\"" + t2.getText() + "\"";
            String mname = "\"" + t3.getText() + "\"";
            String gname = "\"" + t9.getText() + "\"";
            String phno = "\"" + t10.getText() + "\"";
            String dob = "";
            first=first.substring(1);
            dob = ((JTextField) dateChooser.getDateEditor().getUiComponent()).getText();
            String gender = null;
            if (r1.isSelected())
                gender = "\"" + "Male" + "\"";
            else if (r2.isSelected())
                gender = "\"" + "Female" + "\"";
            String email = "\"" + t4.getText() + "\"";
            String marital = null;
            if (r3.isSelected())
                marital = "\"" + "Married" + "\"";
            else if (r4.isSelected())
                marital = "\"" + "Unmarried" + "\"";
            else if (r5.isSelected())
                marital = "\"" + "Others" + "\"";
            String address = "\"" + t5.getText() + "\"";
            String city = "\"" + t6.getText() + "\"";
            String pincode = "\"" + t7.getText() + "\"";
            String state = "\""+ (String) c6.getSelectedItem() + "\"";
            String aadhar = "\"" + t11.getText() + "\"";
            String pan = "\"" + t12.getText() + "\"";
            String religion = "";
            religion = "\"" + (String) c1.getSelectedItem() + "\"";
            String designation = "";
            designation = "\"" + (String) c2.getSelectedItem() + "\"";
            String qualification = "";
            qualification = "\"" + (String) c3.getSelectedItem() + "\"";
            String etype = "";
            if (r6.isSelected())
                etype = "\"" + "Permarent" + "\"";
            else if (r7.isSelected())
                etype = "\"" + "contactual" + "\"";
            String APD = "";
            APD = ((JTextField) dateChooser1.getDateEditor().getUiComponent()).getText();
            String posting = "";
            posting = "\"" + (String) c4.getSelectedItem() + "\"";
            String catagory = "";
            catagory = "\"" + (String) c5.getSelectedItem() + "\"";
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MMM/yyyy");
            LocalDateTime now = LocalDateTime.now();
            String doj = "\"" + dtf.format(now) + "\"";
            try {
                if (t1.getText().equals("") || t2.getText().equals("") || t3.getText().equals("") || t4.getText().equals("") || t5.getText().equals("") || t6.getText().equals("") || t7.getText().equals("") || t9.getText().equals("") || t10.getText().equals("") || t11.getText().equals("") || t12.getText().equals("") || dob == "" || gender == null || marital == null || religion == null || designation == null || qualification == null || etype == null || APD == null || posting == null || catagory == null ||state==null) {
                    JOptionPane.showMessageDialog(null, "Fill all the required fields");
                } else {
                    int p=0;
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    Connection conn = null;
                    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/bank", "root", "");
                    Statement s = conn.createStatement();
                    String s8 = "INSERT INTO employee (name,fname,mother,gname,mno,dob,gender,eadd,ms,address,city,pincode,state,aadhar,pan,religion,designation,qualification,toj,ald,pop,doj,pin) VALUES ('" + name + "','" + fname + "','" + mname + "','" + gname + "','" + phno + "','" + dob + "','" + gender + "','" + email + "','" + marital + "','" + address + "','" + city + "','" + pincode + "','" + state + "','" + aadhar + "','" + pan + "','" + religion + "','" + designation + "','" + qualification + "','" + etype + "','" + APD + "','" + posting + "','" + doj + "','" + first + "')";
                    s.execute(s8);
                    String q = "Select eid from employee WHERE name='"+name+"' and fname='"+fname+"' and mother='"+mname+"' and pin='"+first+"' and mno='"+phno+"' and pincode='"+pincode+"'";
                    Statement st1 = conn.createStatement();
                    ResultSet rs = st1.executeQuery(q);
                    while (rs.next()) {
                        p=rs.getInt("eid");
                    }
                    System.out.println(p);
                    String s9="UPDATE employee SET eid="+p+" WHERE name='"+name+"' and fname='"+fname+"' and mother='"+mname+"' and pin='"+first+"' and mno='"+phno+"' and pincode='"+pincode+"'";
                    s.execute(s9);
                    JOptionPane.showMessageDialog(null, "Incert Successfully");
                    JOptionPane.showMessageDialog(null, "employee id : " + p + "\n Pin:" + first);
                    System.exit(0);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

        } else if (ae.getSource() == b2) {
            System.exit(0);
        }
    }

    public static void main(String[] args) {
        new Empadd();
    }
}